export const AppConstant = {
    bearer: 'Bearer',
    expire_session: 'Session expires please login again!!',
    invalid_token: 'Invalid access token',
    url_not_present_error: 'The request URL must be provided to the LoadingService.setLoading function',
    authentication_failed: 'Authentication failed!! Try again',
    login: 'Login',
    session_token_id: 'id_token',
    session_user_name: 'user_name',
    session_expire_at: 'expires_at',
    multipart_form: 'multipart/form-data',
    mandatory_origin: 'Origin is mandatory parameter with minimum 3 character',
    mandatory_parameter: 'Mandatory parameter',
    query_param_origin: 'origin',
    query_param_departure_date: 'departureDate',
    query_param_one_way: 'oneWay',
    query_param_duration: 'duration',
    query_param_non_stop: 'nonStop',
    query_param_max_price: 'maxPrice',
    query_param_view_by: 'viewBy',
    header_amadeus_json: 'application/vnd.amadeus+json',
    header_json: 'application/json',
    data_not_available: 'Data not available',
    subtype: 'Sub type',
    name: 'Name',
    departure_date_format: 'yyyy-MM-dd',
    flight_dates: 'Flight Dates',
    flight_offers: 'Flight Offers',
    min_max_day_validation_msg: 'Min day cannot be greater then  max day!!',
    duration: 'Duration'
}
